# Generated by Django 5.2.6 on 2025-10-02 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_alter_appointment_psychologist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Notas privadas del profesional sobre la sesión.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_note', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Nota de Sesión',
                'verbose_name_plural': 'Notas de Sesión',
                'db_table': 'session_notes',
                'ordering': ['-appointment__appointment_date'],
            },
        ),
    ]
