# Generated by Django 5.2.6 on 2025-10-02 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='clinical_documents/%Y/%m/%d/')),
                ('description', models.CharField(help_text='Descripción o título del documento.', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'user_type': 'professional'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Clínico',
                'verbose_name_plural': 'Documentos Clínicos',
                'db_table': 'clinical_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
