# Generated by Django 5.2.6 on 2025-10-06 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_history', '0002_clinicaldocument'),
        ('users', '0003_alter_customuser_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalHistory',
            fields=[
                ('patient', models.OneToOneField(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clinical_history', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('consultation_reason', models.TextField(blank=True, help_text='Frase textual del paciente sobre el motivo de consulta.')),
                ('history_of_illness', models.TextField(blank=True, help_text='Relato cronológico de la enfermedad actual (HEA).')),
                ('personal_pathological_history', models.TextField(blank=True, help_text='Enfermedades previas, cirugías, trastornos mentales, etc.')),
                ('family_history', models.TextField(blank=True, help_text='Trastornos mentales, suicidio, adicciones en la familia.')),
                ('personal_non_pathological_history', models.JSONField(blank=True, default=dict, help_text='Hábitos de alimentación, sueño, consumo de sustancias, etc.')),
                ('mental_examination', models.JSONField(blank=True, default=dict, help_text='Resultados de la exploración mental (conciencia, orientación, lenguaje, etc.).')),
                ('complementary_tests', models.TextField(blank=True, help_text='Resultados de pruebas de laboratorio, gabinete o psicométricas.')),
                ('diagnoses', models.JSONField(blank=True, default=list, help_text='Lista de diagnósticos (principal y secundarios) con códigos CIE-10/DSM-5.')),
                ('therapeutic_plan', models.JSONField(blank=True, default=dict, help_text='Plan farmacológico, psicoterapéutico e intervenciones sociales.')),
                ('risk_assessment', models.JSONField(blank=True, default=dict, help_text='Evaluación de riesgos (autolesión, heteroagresión, recaída).')),
                ('sensitive_topics', models.TextField(blank=True, help_text='Temas delicados a tratar con cuidado.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Profesional que creó el historial.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_histories', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, help_text='Último profesional que actualizó el historial.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial Clínico',
                'verbose_name_plural': 'Historiales Clínicos',
            },
        ),
    ]
